".zsh_includes.d/git_ohmyzsh":
  type: file
  url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/git/git.plugin.zsh
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
